version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/client-build
    overwrite: yes
permissions:
  - object: /home/ubuntu/client-build
    owner: root
    group: root
    mode: 755
hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 1000
      runas: root
